import { type NextPage } from "next";
import Head from "next/head";
// import { SignInButton, useUser } from "@clerk/nextjs";
// import { api } from "~/utils/api";
// import Image from "next/image";
// import { LoadingPage } from "~/components/loading";
// import Link from "next/link";
// import { useState } from "react";

// const CreateProductWizard = () => {
//   const { user } = useUser();

//   if (!user) return null;

//   return (
//     <div className="flex gap-3 w-full">
//       <Image
//         src={user.profileImageUrl}
//         alt="Profile image"
//         className="rounded-full"
//         width={56}
//         height={56}
//       />
      
//       <Link href="/tasks">
//         Go to Task
//       </Link>
//     </div>
//   );
// };

// const List = () => {
//   const { data, isLoading: productsLoading } = api.products.getAll.useQuery();
//   if (productsLoading) return <LoadingPage />;
//   if (!data) return <div>Error</div>;

//   return (
//     <div>
//       {data.map((product) => (
//         <div key={product.id} className="border-b border-slate-400 p-8">{product.name}</div>
//       ))}
//     </div>
//   );
// };
// interface Feature {
//   id: string;
//   name: string;
//   description: string;
// }
// interface FeatureItemProps {
//   item: Feature;
// }
// const FeatureItem: React.FC<FeatureItemProps> = ({ item }) => {
//   return (
//     <div className="m-6">
//       <div className="border-green-300 border-2 rounded-lg text-center text-gray-50 py-4 px-8 whitespace-nowrap">
//         { item.name }
//       </div>
//       <p className="text-gray-50 text-center p-4">
//         { item.description }
//       </p>
//     </div>
//   );
// };

const MainModule = () => {
  return (
    <div className="relative w-full h-full overflow-hidden m-0 flex flex-col justify-center items-center">
      <div className="p-10 flex items-center">
        <h2 className="text-white not-italic text-5xl">
          Hybrid Fashion
        </h2>
        <div className="rounded-lg bg-gradient-to-b from-green-basic to-blue-basic text-black text-5xl flex justify-center items-center w-24.25 h-15.25 mx-8">
          AI
        </div>
        <h2 className="text-white not-italic text-5xl">
          数字模特换装平台
        </h2>
      </div>
      <div className="bg-clip-text bg-gradient-to-b from-blue-back-100 via-green-back via-99% to-blue-back text-transparent text-4xl">
        让每件衣服都有合适的模特
      </div>
      <div className="flex items-center justify-center mt-8">
        <div className="w-61.5 h-61.5 rounded-full border border-white mr-7.1"></div>
        <div className="w-61.5 h-61.5 rounded-full border border-white mr-7.1"></div>
        <div className="w-61.5 h-61.5 rounded-full border border-white"></div>
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  // const { isLoaded: userLoaded } = useUser();

  // api.products.getAll.useQuery();

  // if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Hybride Fashion</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainModule />
    </>
  );
};

export default Home;
