import { type NextPage } from "next";
import Head from "next/head";
import { AboutModule } from "~/components/home/about";
import { IntroductModule } from "~/components/home/introduct";
import { MainModule } from "~/components/home/main";
import { SecondModule } from "~/components/home/second";
// import { SignInButton, useUser } from "@clerk/nextjs";
// import { api } from "~/utils/api";
// import { LoadingPage } from "~/components/loading";
// import Link from "next/link";
// import { useState } from "react";


const Home: NextPage = () => {
  // const { isLoaded: userLoaded } = useUser();

  // api.products.getAll.useQuery();

  // if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Hybride Fashion</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainModule />
      <SecondModule />
      <IntroductModule />
      <AboutModule />
    </>
  );
};

export default Home;
